# Generated by Django 3.0 on 2022-06-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='CornerProperty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='Food_Available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='Housekeeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='LaundaryService',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='Maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='amount',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='rentFor',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='seatAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=300),
        ),
    ]
